Team-WeQuiz/wequiz

- chatty-be/src/main/java/com/chatty/chatty/config/WebConfig.java
- chatty-be/src/main/java/com/chatty/chatty/config/filter/CorsFilter.java
> [BE] CORS 설정

- model/app/app.py
- model/app/data/vectorizer.py
- resolves #94 
- 백엔드와 integration 테스트를 위해 임시 API를 구현함
- 파일id 입력 받으면 -> [s3에서 파일 읽어오기, 파일파싱, 문제생성] -> 백에 결과 반환
일케 전달받고 전달해주면 되는지 백에서 체크 부탁드림다
*비고
numOfQuiz, type, keyword, description 기능은 아직 구현하지 않아 임의의 값으로 채워넣음.
> 임시 integration API

- chatty-be/build.gradle
- chatty-be/src/main/java/com/chatty/chatty/config/WebSocketConfig.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/config/RestClientConfig.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/QuizRoomController.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/MakeQuizRequest.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/MakeQuizResponse.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/MakeRoomRequest.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/MakeRoomResponse.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/entity/QuizRoom.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/repository/QuizRoomRepository.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/service/ModelService.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
- #74 
- 퀴즈룸 검색, 생성 api 구현
- restclient를 사용해 ml 서버에 문제 생성 요청 api 구현
- 방 생성 요청 받으면 ml에 문제 생성 요청 후 프론트에 문제 반환
- STOMP 기반 웹소켓 config 작성
로컬로 방 생성 api 테스트 해봤을 때 되긴 함...
~~퀴즈방에 데이터가 2개씩 들어가서 고쳐야 함~~
STOMP 기반 웹소켓 사용했습니다
```
function connect() {
var socket = new WebSocket('/ws-connection');
stompClient = Stomp.over(socket);
stompClient.connect({}, function () {
setConnected(true);
stompClient.subscribe('/subscribe/rooms/5', function (greeting) {
console.log(greeting.body);
});
});
}
```
프론트에서 이런 식으로 연결하면 된다고 합니다
방 생성에는 웹소켓 사용할 필요 없고 플레이어 입퇴장(방 생성 시 생성자 입장 포함) 시 프론트에서 소켓 연결해주면 되는 것 같습니다
연결된 소켓 내에서 메세지, 이모지 주고받는 컨트롤러 구현 예정입니당
아직 공부 중이라 틀릴 수도 잇슴니다
참고 자료: https://tecoble.techcourse.co.kr/post/2021-09-05-web-socket-practice/
> [BE] 문제 생성 요청, 퀴즈 방 생성

- model/.gitignore
- model/app/app.py
- model/app/data/splitter.py
> Config: config aws access key

- chatty-fe/Dockerfile
- chatty-fe/next.config.js
- #103 
- 도커 파일을 추가했읍니다.
1. 쉬운 관리를 위해 docker desktop을 설치하길 권장합니다.
2. 해당 도커파일이 있는 경로로 들어갑니다.
3. `docker build -t wequiz-front .` 명령어를 실행합니다
4. `docker run -p 3000:3000 wequiz-front` 명령어를 실행합니다.
5. `localhost:3000` 으로 접속합니다.
> [FE] 도커 파일 추가 

- chatty-be/Dockerfile
- chatty-be/build.gradle
- chatty-be/src/main/java/com/chatty/chatty/quizroom/config/RestClientConfig.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/service/ModelService.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
- chatty-be/src/main/resources/application.yml
- docker-compose.yml
- #106 
- Spring application Dockerfile 생성
- docker-compose.yml 작성
- swagger 설정 (http://localhost:8080/api)
`docker-compose up -d --build` 명령어를 이용해주세요
> [BE] Docker 및 Swagger 설정

- docker-compose.yml
> [FE] docker compose 프론트 추가

- chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/MakeRoomResponse.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/entity/QuizRoom.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
- #117 
- QuizRoom Entity에서 link 삭제
> [BE] QuizRoom Entity에서 link 삭제

- model/.gitignore
- model/app/app.py
- model/app/data/splitter.py
- #133 
- 문제 반환 형식 수정 (list object -> list string)
> 문제 반환 형식 수정 (list object -> list string)

- chatty-be/src/main/java/com/chatty/chatty/player/entity/Player.java
- chatty-be/src/main/java/com/chatty/chatty/user/entity/User.java
- #149 
- User Entity에서 password, loginType not null 설정
- Player Entity에서 roomId, userId not null 설정
> [BE] Entity not null 설정

- model/app/app.py
- #133 
- 리스트 안에 각각의 문제 객체를 스트링화하도록 수정
> 문제 반환 스트링 재수정

- chatty-fe/package-lock.json
- chatty-fe/package.json
- chatty-fe/src/app/(auth)/sign-in/google/callback/page.tsx
- chatty-fe/src/app/(auth)/sign-in/kakao/callback/page.tsx
- chatty-fe/src/app/(auth)/sign-in/page.tsx
- chatty-fe/src/app/(auth)/sign-up/page.tsx
- chatty-fe/src/app/(game)/create-room/page.tsx
- chatty-fe/src/app/_api/auth.ts
- chatty-fe/src/app/_api/client.ts
- chatty-fe/src/app/_api/createRoom.ts
- chatty-fe/src/app/_lib/auth.ts
- chatty-fe/src/app/_store/useAuthStore.ts
- #128 
- api 레이어 구현
- 방만들기 api 요청 구현
> [FE] api 리팩토링, 방만들기 요청

- docker-compose.yml
> [ML] Docker compose에 ml 컨테이너 추가

- model/app/app.py
> [ML] 문제 반환 형식 string -> 객체 로 다시 변환

- model/app/app.py
- model/app/data/prob_generator.py
- model/app/data/summarizer.py
- model/app/model/chain.py
- resolves #95 
- 문서 요약 기능 구현
- 문서 요약, 문제 생성 기능 모듈화
- 문제 및 요약 생성 api 리팩토링
yield로 요약을 젤 처음 리턴하고
이후 numOfQuiz만큼 문제 yield로 리턴
추후 모든 문제 생성 완료되면 dynamodb로 push하는 기능 구현 필요
> 문제 요약 API 구현

- model/app/app.py
- model/app/data/marker.py
- model/app/model/chain.py
- model/app/model/prompt.py
- resolves #156
- 그냥 일단 문제 형식과 관련 없이 gpt가 채점해주는 걸로 기본 체인 구성함
> 기본적인 채점 API 구현

- chatty-fe/package-lock.json
- chatty-fe/package.json
- chatty-fe/src/app/_api/auth.ts
- chatty-fe/src/app/_lib/auth.ts
- chatty-fe/src/app/_lib/keys.ts
- chatty-fe/src/app/api/s3-keys/getSecrets/route.ts
- chatty-fe/src/app/api/s3-upload/complete/route.ts
- chatty-fe/src/app/api/s3-upload/get-geturl/route.ts
- chatty-fe/src/app/api/s3-upload/get-id/route.ts
- chatty-fe/src/app/api/s3-upload/get-url/route.ts
- chatty-fe/src/app/page.tsx
> [FE] AWS Secret Manager 마이그레이션

- model/app/app.py
- model/app/data/prob_generator.py
- model/app/data/settings.py
- model/app/data/splitter.py
- model/app/data/vectorizer.py
- #195 
- 문제 리턴 형식 수정
- 다이나모디비 연결 (테이블명: wequiz-quiz)
> [ML] 문제 생성 API 수정, DB 재연결

- chatty-be/build.gradle
- chatty-be/src/main/resources/application-local.yml
> [BE] 데이터베이스를 mysql로 변경

- chatty-be/Dockerfile
- 백엔드 CI 작업을 위해 도커 파일 수정
- 내용을 적어주세요.
> [BE]Config: 백엔드 도커 파일 수정

- chatty-be/src/main/resources/application-local.yml
- #204 
- 오타 수정
- ci 확인 작업을 위해 pr 생성
> [feat/#204] :bug: Fix: db 설정 오타 수정

- chatty-be/Dockerfile
- chatty-be/src/main/resources/application-prod.yml
- ec2 내에서 datasource url 을 localhost 가 아닌 container 명으로 지정해야 함에 따른 파일 수정
- application-prod.yml 을 생성하여 배포환경 설정 분리
> [BE] :bug: Fix: docker에서 datasource url를 맞게 수정

- model/app/app.py
- model/app/schema.py
- resolves #181 
코드가 너무 더러워 이슈로 리팩토링 했습니다.
큰 차이는 없음
- 채점 API 리팩토링
- 문제 생성 API 리팩토링
> [ML] API 코드 리팩토링

- model/.gitignore
- model/app/app.py
- model/app/data/prob_generator.py
- model/app/schema.py
- resolves #222
- quiz-set id는 ml서버에서 생성하도록 수정했습니다.
API 명세서 참고 부탁드림다
https://www.notion.so/API-8448ee5aa1d640a28832037fee4b7e2a
> [ML] 문제 생성, 채점 API DTO 수정

- model/app/app.py
- model/app/data/loader.py
- model/app/data/parsers/pdf.py
- #188 
- S3 Loader 구현 했습니다.
- test api 생성해서 테스트 진행 중입니다.
> [ML] (#188) S3 Loader 구현, test api 테스트 진행 중

- model/Dockerfile
- resolves #229 
- Dockerfile 수정
> [ML] Docker에서 OCR 기능 터지는 문제 해결

- chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/CreateRoomResponse.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
> [feat/#219] :bug: Fix: 방 생성할 때 description과 roomid 함께 반환

- chatty-fe/src/app/(game)/layout.tsx
- chatty-fe/src/app/(game)/waiting-room/[id]/_utils/stomp.ts
- chatty-fe/src/app/(game)/waiting-room/[id]/page.tsx
- chatty-fe/src/app/_api/client.ts
- #226 
- 페이지를 이동하거나 창을 닫을 경우 leave 메시지 보냄
- 마지막 남은 사람이 떠날 경우 end 메시지
> [FE] 채팅방 나가기, 종료 연결

- chatty-fe/src/app/(game)/create-room/_components/FileUploadBox.css.ts
- chatty-fe/src/app/(game)/create-room/_components/FileUploadBox.tsx
- chatty-fe/src/app/(game)/create-room/page.tsx
- chatty-fe/src/app/(game)/layout.tsx
- chatty-fe/src/app/(game)/waiting-room/[id]/_utils/stomp.ts
- chatty-fe/src/app/(game)/waiting-room/[id]/page.tsx
- chatty-fe/src/app/_api/client.ts
- chatty-fe/src/app/_api/createRoom.ts
- #235 
- s3에 pdf파일을 업로드하는 방식에서 문제 생성시 백엔드로 바로 전달하는 방식으로 변경
- 기존 fileUploadBox를 수정하고 응답을 기다리는 동안 버튼은 로딩표시가 되도록 수정했습니다.
- 필요없는 코드는 일단 주석처리했는데 삭제는 준형님이... 제 손으로 차마 할 수 없네요...
> [FE] 파일 업로드 방식 변경

- model/app/app.py
- model/app/data/generator.py
- model/app/model/chain.py
- model/app/utils/security.py
- #188 
- 요약 비동기 생성 다시 제거했습니다.
- async_generator는 jsonable_econder가 안 된다며 fastapi에서 자꾸 뭐라함
- 성능 차이 없어서 제거
> [ML] Revert: 요약 비동기 제거

- model/app/app.py
- model/app/data/preprocessor.py
- model/app/model/chain.py
- #245 
- gpt-3.5-turbo-instruct -> gpt-3.5-turbo-0125
> [ML] 모델 변경

- model/app/app.py
- model/app/data/preprocessor.py
- model/app/data/settings.py
- model/app/model/chain.py
- #245 
- 텍스트 전처리 추가
- split 기준 수정
- 속도는 여전히 문제다
요약 결과물이 더 좋아진거 테스트 한 번만에 보였음. 그래도 한 두번 더 테스트 해봐야함.
[Notion](https://www.notion.so/6f4f44a6f3fd40f5b0d02bfbf75cb89b?pvs=4#c5e75e916a8847db81f9b39e73550aee)
(좌) 수정 전
(우) 수정 후
> [ML] 텍스트 전처리, 요약 테스트

- model/app/app.py
- model/app/data/preprocessor.py
- model/app/model/prompt.py
- #252 
- 이미지 처리 off
- 요약 생성 길이 제한
[[Notion] :test_tube: 문제 생성 실험실](https://www.notion.so/6f4f44a6f3fd40f5b0d02bfbf75cb89b)
> [ML] 파싱, 요약 시간 조정

- model/app/app.py
- model/app/data/preprocessor.py
- model/app/model/chain.py
- model/app/model/prompt.py
- #254 
text split 속도 및 퀄리티가 가장 괜찮은 조합 선정
아래 내용으로 채택
- chunk: 3000
- overlap: 500
- max token: 4000
- 프롬프트 언어: en
[[Notion] :test_tube: 문제 생성 실험실](https://www.notion.so/6f4f44a6f3fd40f5b0d02bfbf75cb89b)
> [ML] Text split 최적화

- model/app/app.py
- model/app/data/loader.py
- model/app/data/preprocessor.py
- model/app/utils/hash.py
- resolves #263 
- user_id + timestamp에 sha256 해시함수 적용
- 빈 경로의 경우 예외처리
> [ML] minio에서 파일 가져오는 폴더 경로 수정

- chatty-be/src/main/java/com/chatty/chatty/common/util/Sha256Encrypt.java
- chatty-be/src/main/java/com/chatty/chatty/config/minio/MinioRepository.java
- chatty-be/src/main/java/com/chatty/chatty/game/service/model/ModelService.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/exception/FileExceptionType.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
- #262 
- 기존 : userId/pdf/file-[uuid]
- 변경 : sha256(userid-timestamp)/pdf/file-[uuid]
> [BE] minio에 저장하는 경로 변경

- chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/QuizRoomController.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/CreateRoomRequest.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/RoomDetailResponse.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/RoomQuizResponse.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/entity/QuizRoom.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
- #269
- `GET : /rooms/{roomId}`
- 퀴즈룸 관련 DTO 에서 timeLImit 삭제
> [BE] :bug: Fix: 퀴즈룸 상세정보 api 수정

- model/README.md
- model/app/app.py
- model/app/data/generator.py
- model/app/model/chain.py
- model/app/model/prompt.py
- #250 
오늘 integration test를 위해 문제 생성 API 임시로 수정 (하드 코딩 제거!!!)
(앞으로도 동일한 방식을 사용하지만 수정할 것들이 더 많이 있슴다,..)
- 요약 중간 산출물을 소스로 사용해서 문제 생성하도록 수정
- 프롬프트 수정
> [ML] 문제 생성 방식 수정 (임시)

- chatty-be/src/main/java/com/chatty/chatty/common/util/ThreadSleep.java
- chatty-be/src/main/java/com/chatty/chatty/game/controller/GameController.java
- chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/SubmitAnswerRequest.java
- chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/SubmitAnswerResponse.java
- chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/model/MarkRequest.java
- chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/model/MarkResponse.java
- chatty-be/src/main/java/com/chatty/chatty/game/domain/Answer.java
- chatty-be/src/main/java/com/chatty/chatty/game/domain/AnswerData.java
- chatty-be/src/main/java/com/chatty/chatty/game/domain/QuizData.java
- chatty-be/src/main/java/com/chatty/chatty/game/domain/SubmitStatus.java
- chatty-be/src/main/java/com/chatty/chatty/game/repository/AnswerRepository.java
- chatty-be/src/main/java/com/chatty/chatty/game/repository/GameRepository.java
- chatty-be/src/main/java/com/chatty/chatty/game/repository/dynamodb/DynamoDBRepository.java
- chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
- chatty-be/src/main/java/com/chatty/chatty/game/service/dynamodb/DynamoDBService.java
- chatty-be/src/main/java/com/chatty/chatty/game/service/model/ModelService.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/QuizRoomController.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
> [BE] 답안 받아서 채점요청

- chatty-be/src/main/java/com/chatty/chatty/game/controller/GameController.java
- chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
- #278 
- fillQuiz를 sendQuiz에서 실행하도록 변경
- createRoom에 @ Transactional 다시 추가
- submit 경로 수정
> [BE] fillQuiz를 sendQuiz에서 실행하도록 변경

- chatty-fe/src/app/(game)/create-room/page.tsx
- chatty-fe/src/app/(game)/main-lobby/_components/GameCard/GameCard.css.ts
- chatty-fe/src/app/(game)/main-lobby/_components/GameCard/GameCard.tsx
- chatty-fe/src/app/(game)/main-lobby/_components/GameListGrid/GameListGrid.tsx
- chatty-fe/src/app/(game)/main-lobby/page.tsx
- chatty-fe/src/app/(game)/waiting-room/[id]/_components/QuizInfoCard/QuizInfoCard.css.ts
- chatty-fe/src/app/(game)/waiting-room/[id]/_components/QuizInfoCard/QuizInfoCard.tsx
- chatty-fe/src/app/(game)/waiting-room/[id]/_components/QuizSummaryCard/QuizSummaryCard.css.ts
- chatty-fe/src/app/(game)/waiting-room/[id]/_components/QuizSummaryCard/QuizSummaryCard.tsx
- chatty-fe/src/app/(game)/waiting-room/[id]/page.css.ts
- chatty-fe/src/app/(game)/waiting-room/[id]/page.tsx
- chatty-fe/src/app/_api/createRoom.ts
- chatty-fe/src/app/_api/quiz.ts
- chatty-fe/src/app/_components/Header.tsx
- #275
- description topic 구독 -> quiz info get 요청 -> description 받아오기 순서대로 구현했습니다.
> [FE] 대기방에서 퀴즈 요약 description 가져오기

- model/Dockerfile
- model/app/data/keyword.py
- model/mecab_install.sh
- resolves #325 
- 한글 -> mecab, 영어 -> nltk 사용하도록 수정
이번에 빌드 오류 나면 이 태스크는 포기해야겠음 크게 중요한 부분도 아니고 개같은거
> [ML] 언어에 따른 토크나이저 사용

- chatty-fe/src/app/(game)/layout.css.ts
- chatty-fe/src/app/(game)/waiting-room/[id]/_components/QuizInfoCard/QuizInfoCard.css.ts
- chatty-fe/src/app/(game)/waiting-room/[id]/_components/QuizInfoCard/QuizInfoCard.tsx
- chatty-fe/src/app/(game)/waiting-room/[id]/_components/QuizSummaryCard/QuizSummaryCard.css.ts
- chatty-fe/src/app/(game)/waiting-room/[id]/_components/QuizSummaryCard/QuizSummaryCard.tsx
- chatty-fe/src/app/(game)/waiting-room/[id]/_components/ReadyButton/ReadyButton.css.ts
- chatty-fe/src/app/(game)/waiting-room/[id]/_components/UserCard/UserCard.css.ts
- chatty-fe/src/app/(game)/waiting-room/[id]/_components/UserCard/UserCard.tsx
- chatty-fe/src/app/(game)/waiting-room/[id]/_components/UserList/UserList.css.ts
- chatty-fe/src/app/(game)/waiting-room/[id]/_components/UserList/UserList.tsx
- chatty-fe/src/app/(game)/waiting-room/[id]/page.css.ts
- #316 
- 모바일을 위한 반응형 레이아웃을 재구성 했습니다.
> [FE] 대기방 반응형 디테일 수정

- chatty-fe/src/app/(auth)/sign-in/page.tsx
- chatty-fe/src/app/_api/auth.ts
- #340 
- localhost => wequiz.kr
> [FE] redirect uri 수정

- chatty-fe/src/app/(auth)/sign-in/page.tsx
- chatty-fe/src/app/(auth)/sign-up/page.tsx
- chatty-fe/src/app/(game)/create-room/page.css.ts
- chatty-fe/src/app/(game)/create-room/page.tsx
- chatty-fe/src/app/_api/auth.ts
- chatty-fe/src/app/_api/createRoom.ts
- chatty-fe/src/app/_api/quiz.ts
- chatty-fe/src/app/_components/TextInputField.tsx
- chatty-fe/src/app/page.tsx
- chatty-fe/src/middleware.ts
- #301 
- 파일 최대크기는 아직 정해지지 않아서 적용하지 않았습니다.
> [FE] input 길이 제한, 응답 에러 처리

- chatty-be/src/main/java/com/chatty/chatty/config/minio/MinioRepository.java
- chatty-be/src/main/java/com/chatty/chatty/config/minio/exception/MinioExceptionType.java
- chatty-be/src/main/java/com/chatty/chatty/game/exception/ModelException.java
- chatty-be/src/main/java/com/chatty/chatty/game/exception/ModelExceptionType.java
- chatty-be/src/main/java/com/chatty/chatty/game/service/model/ModelService.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
- chatty-be/src/main/java/com/chatty/chatty/user/controller/UserController.java
- chatty-be/src/main/java/com/chatty/chatty/user/service/UserService.java
- #341 
- pdf 토큰이 적은 경우 ML에서 500에러를 받아 클라에 서버에 커스텀 Exception 전달
- exception 발생하는 경우 minio에 올라간 파일 삭제
> [BE] :sparkles: Feat: 요청하는 pdf의 토큰이 적을 경우 에러 반환

- model/app/app.py
- model/requirements.txt
- #354 
- dynamodb랑 소통하는 부분 비동기처리
- 문제 생성 api쪽은 병렬 추가
> [ML] 비동기처리

- chatty-fe/src/app/(auth)/sign-in/google/callback/page.css.ts
- chatty-fe/src/app/(auth)/sign-in/google/callback/page.tsx
- chatty-fe/src/app/(auth)/sign-in/kakao/callback/page.css.ts
- chatty-fe/src/app/(auth)/sign-in/kakao/callback/page.tsx
- chatty-fe/src/app/(game)/create-room/_components/QuestionMaker/QuestionMaker.tsx
- chatty-fe/src/app/(game)/create-room/page.tsx
- #356 
- 방만들기 페이지에서 문제 제작 / 리스트 선택 순서를 변경 하였읍니다.
- 콜백 페이지 디자인을 수정하였읍니다.
> [FE] 콜백페이지, 방만들기 순서

- chatty-fe/src/app/(game)/@modal/(.)enter-room/[id]/page.tsx
- chatty-fe/src/app/(game)/enter-room/[id]/_component/EnteringModals/EnteringModals.tsx
- chatty-fe/src/app/(game)/enter-room/[id]/_component/NicknameModal/NicknameModal.tsx
- chatty-fe/src/app/(game)/mypage/_component/UserInfoForm/UserInfoForm.tsx
- chatty-fe/src/app/(game)/waiting-room/[id]/_components/QuizInfoCard/QuizInfoCard.tsx
- chatty-fe/src/app/(game)/waiting-room/[id]/_components/QuizSummaryCard/QuizSummaryCard.tsx
- chatty-fe/src/app/(game)/waiting-room/[id]/page.tsx
- chatty-fe/src/app/_api/quiz.ts
- #365 
- 대기방 파일 요약 타이핑 효과 수정
- 방 끝났을 경우 대기방, 입장 모달에서 메인 로비로 보내기
> [FE] 대기방 파일 요약 타이핑 효과 수정

- chatty-be/src/main/java/com/chatty/chatty/auth/config/AuthConfig.java
- chatty-be/src/main/java/com/chatty/chatty/config/minio/MinioRepository.java
- chatty-be/src/main/java/com/chatty/chatty/config/minio/exception/MinioExceptionType.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
- chatty-be/src/main/java/com/chatty/chatty/user/controller/UserController.java
- chatty-be/src/main/java/com/chatty/chatty/user/controller/dto/ProfileImageRequest.java
- chatty-be/src/main/java/com/chatty/chatty/user/entity/User.java
- chatty-be/src/main/java/com/chatty/chatty/user/service/UserService.java
- chatty-be/src/main/resources/application-local.yml
- chatty-be/src/main/resources/application.yml
- #367 
- minio에서 프로필 사진 저장 및 조회 기능
> [BE] 프로필 사진 업로드 및 조회 기능

- chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/SubmitAnswerResponse.java
- chatty-be/src/main/java/com/chatty/chatty/game/domain/AnswerData.java
- chatty-be/src/main/java/com/chatty/chatty/game/domain/SubmitStatus.java
- chatty-be/src/main/java/com/chatty/chatty/game/repository/AnswerRepository.java
- chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
- #385 
- 모두 제출인지는 반환 안 하고, 과반수인지 아닌지를 
Boolean isMajority로 반환합니다
- synchronized를 제거해보았습니다...
- 모두 제출하였는지는 유저 제출 상태에서 true의 개수로 판단합니다.
> [BE] 제출 상태 DTO 수정

- chatty-fe/src/app/(game)/mypage/_component/UserQuizList/UserQuizList.tsx
- chatty-fe/src/app/(game)/quiz-room/[id]/page.tsx
> [FE] 제출 상태 DTO 수정 반영, submit message 수정

- chatty-be/src/main/java/com/chatty/chatty/game/domain/QuizData.java
- chatty-be/src/main/java/com/chatty/chatty/game/exception/GameExceptionType.java
- chatty-be/src/main/java/com/chatty/chatty/game/repository/AnswerRepository.java
- chatty-be/src/main/java/com/chatty/chatty/game/repository/GameRepository.java
- chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
> Revert "[BE] 퀴즈 삭제 후 다음 퀴즈 넘기게 수정"

- chatty-be/src/main/java/com/chatty/chatty/config/minio/MinioRepository.java
- chatty-be/src/main/java/com/chatty/chatty/user/service/UserService.java
- #395 
- 프로필 사진 변경 시 minio에서 기존 저장되어 있던 프로필 사진 삭제
> [BE] :bug: Fix: 프로필 사진 변경 시 minio에서 기존 저장되어 있던 프로필 사진 삭제

- chatty-be/src/main/java/com/chatty/chatty/common/util/RandomCodeGenerator.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/QuizRoomController.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/CodeRequestDTO.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/CreateRoomRequest.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/RoomDetailResponse.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/RoomIdResponse.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/entity/QuizRoom.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/exception/QuizRoomExceptionType.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/repository/QuizRoomRepository.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
- #310 
- 6자리 코드로 방 접속 api
- 방 생성할 때 request에서 `code` 제외했습니다.
- 방 상세 api에서 response에 `code`를 추가했습니다.
- 퀴즈룸 리스트 페이지에 최소 1명의 인원이 있는 방이 뜨도록 수정했습니다.
> [BE] 6자리 코드로 방 접속 api

- chatty-be/src/main/java/com/chatty/chatty/game/controller/GameController.java
- chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/CountDownResponse.java
- chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
- #402 
- 퀴즈 카운트 구독
`/sub/rooms/{roomId}/quizCount`
- 중간 결과 카운트 구독
`/sub/rooms/{roomId}/scoreCount`
- DTO: `Integer second`
> [BE] 카운트다운 구현

- chatty-be/src/main/java/com/chatty/chatty/game/controller/GameController.java
- chatty-be/src/main/java/com/chatty/chatty/game/domain/AnswerData.java
- chatty-be/src/main/java/com/chatty/chatty/game/domain/Phase.java
- chatty-be/src/main/java/com/chatty/chatty/game/repository/PhaseRepository.java
- chatty-be/src/main/java/com/chatty/chatty/game/repository/UserSubmitStatusRepository.java
- chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
- #399 
- Phase를 넣어서 소켓 데이터 전달 단계 구분
- 잼민이가 카운트 다운 구현 완료하면 Phase 상태변화 저장 추가 구현 필요
```
QUIZ_SOLVING,
COUNTDOWN,
RESULT;
```
> [BE] Phase를 넣어서 소켓 데이터 전달 단계 구분

- chatty-fe/next.config.js
- chatty-fe/src/app/(game)/enter-room/[id]/_component/EnteringModals/EnteringModals.tsx
- chatty-fe/src/app/(game)/mypage/_component/ProfileEditor/ProfileEditor.tsx
- chatty-fe/src/app/(game)/waiting-room/[id]/_components/QuizInfoCard/QuizInfoCard.tsx
- chatty-fe/src/app/_api/quiz.ts
> [FE] 방 조회 에러 처리, 프로필 이미지 버그 픽스

- chatty-be/src/main/java/com/chatty/chatty/game/controller/dto/ScoreResponse.java
- chatty-be/src/main/java/com/chatty/chatty/game/domain/ScoreData.java
- chatty-be/src/main/java/com/chatty/chatty/game/domain/UserSubmitStatus.java
- chatty-be/src/main/java/com/chatty/chatty/game/domain/UsersSubmitStatus.java
- chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
- chatty-be/src/main/java/com/chatty/chatty/player/domain/PlayerStatus.java
- chatty-be/src/main/java/com/chatty/chatty/player/domain/PlayersStatus.java
- chatty-be/src/main/java/com/chatty/chatty/player/repository/PlayersStatusRepository.java
- #405 
- user status가 필요한 곳에 프로필 이미지 추가
- 퀴즈 대기방 유저 상태
- 퀴즈 진행할 때 진행률 상태
- 퀴즈 채점 결과
> [BE] user status가 필요한 곳에 프로필 이미지 추가

- chatty-fe/next.config.js
- chatty-fe/src/app/(game)/quiz-room/[id]/_components/ResultModal/ResultModal.css.ts
- chatty-fe/src/app/(game)/quiz-room/[id]/page.tsx
- chatty-fe/src/app/(game)/result/[id]/_components/ResultPageModal/ResultPageModal.css.ts
- chatty-fe/src/app/(game)/result/[id]/_components/ResultPageModal/ResultPageModal.stories.ts
- chatty-fe/src/app/(game)/result/[id]/_components/ResultPageModal/ResultPageModal.tsx
- #397 
- 
ui 수정
게임 비즈니스로 직 다뺴 기
- 내용을 적어주세요.
> [FE] ui수정 게임진행 수정

- chatty-be/src/main/java/com/chatty/chatty/game/domain/QuizData.java
- chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
- chatty-be/src/main/java/com/chatty/chatty/player/repository/PlayersStatusRepository.java
- chatty-be/src/main/java/com/chatty/chatty/user/service/UserService.java
- #407 
- 카운트 다운 관련 메소드에 Phase 저장 및 소켓 호출 반영
- 프로필 이미지 url이 잘못 가던 이슈 수정
> [BE] Phase 저장이 필요한 곳에 추가 반영

- chatty-fe/Dockerfile
> [FE] 도커파일 수정

- chatty-fe/next.config.js
- chatty-fe/src/app/(game)/enter-room/[id]/_component/NicknameModal/NicknameModal.tsx
- chatty-fe/src/app/(game)/waiting-room/[id]/_components/ChatInput/ChatInput.tsx
- chatty-fe/src/app/(game)/waiting-room/[id]/_components/ReadyButton/ReadyButton.tsx
- chatty-fe/src/app/_api/quiz.ts
> [FE] 닉네임 길이 제한, 이미지 hostname 등록

- chatty-fe/src/app/(game)/quiz-room/[id]/page.tsx
> [FE] 상태 초기화

- chatty-be/src/main/java/com/chatty/chatty/game/controller/GameController.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/RoomDetailResponse.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/entity/QuizRoom.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
- #425 
- 룸 상세 정보에 인원 다 차 있는지 여부 전달
> [BE] 룸 상세 정보에 인원 다 차있는지 여부 전달

- chatty-be/src/main/java/com/chatty/chatty/game/controller/GameController.java
- chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
> [BE] 제출 상태 갱신되는대로 전송

- chatty-be/src/main/java/com/chatty/chatty/config/WebSocketEventListener.java
- chatty-be/src/main/java/com/chatty/chatty/game/controller/GameController.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
- #432 
- 웹 소켓 Disconnect 되었을 때 이벤트리스너 구현
- disconnect 될때 퀴즈방 leave 호출
- leave할 때 마지막 사람이 leave 하면 finishRoom으로 사용하지 않는 메모리 관리
- GameController에서 end 로 소켓 보내는 finish 메소드 삭제
-> 이제 유령회원 안 나와요
> [BE] 웹 소켓 Disconnect 되었을 때 이벤트리스너 구현

- chatty-fe/src/app/(game)/@modal/(.)enter-room/[id]/page.tsx
- chatty-fe/src/app/(game)/enter-room/[id]/_component/EnteringModals/EnteringModals.tsx
- chatty-fe/src/app/(game)/quiz-room/[id]/page.tsx
- chatty-fe/src/app/(game)/waiting-room/[id]/_components/QuizInfoCard/QuizInfoCard.tsx
- chatty-fe/src/app/(game)/waiting-room/[id]/page.tsx
- chatty-fe/src/app/_types/QuizInfoType.ts
> [FE] 퀴즈 대기방, 풀이방 리팩토링

- chatty-be/src/main/java/com/chatty/chatty/config/WebSocketEventListener.java
- chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
- chatty-be/src/main/java/com/chatty/chatty/player/domain/PlayersStatus.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
> [BE] :bug: Fix: 커넥션이 끊어 질 때 방 상태에 따라 분기 설정

- chatty-fe/src/app/(game)/mypage/_component/ProfileEditor/ProfileEditor.tsx
- chatty-fe/src/app/(game)/quiz-room/[id]/_components/ResultModal/ResultModal.tsx
- chatty-fe/src/app/(game)/quiz-room/[id]/_components/UserGrid/UserGrid.tsx
- chatty-fe/src/app/(game)/quiz-room/[id]/page.tsx
- chatty-fe/src/app/(game)/waiting-room/[id]/_components/QuizInfoCard/QuizInfoCard.tsx
- chatty-fe/src/app/_store/useUserInfoStore.ts
> [FE] 이미지 null 처리

- model/app/data/generator.py
- model/app/data/settings.py
> [ML] OX퀴즈 채점 오류 수정

- chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
- #431 
- @KRimwoo @ryanbae94 
- 중간 점수 구독 경로 `/sub/rooms/{roomId}/score` 로 바꿔주세요!!
> [BE] 중간 점수 한 명한테만 뜨는 버그 수정

- chatty-be/src/main/java/com/chatty/chatty/auth/support/AuthenticationContext.java
- chatty-be/src/main/java/com/chatty/chatty/config/GlobalMessagingTemplate.java
- chatty-be/src/main/java/com/chatty/chatty/config/WebSocketEventListener.java
- chatty-be/src/main/java/com/chatty/chatty/config/interceptor/StompHandler.java
- chatty-be/src/main/java/com/chatty/chatty/game/controller/GameController.java
- chatty-be/src/main/java/com/chatty/chatty/game/service/GameService.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/controller/dto/QuizResultDTO.java
- chatty-be/src/main/java/com/chatty/chatty/quizroom/service/QuizRoomService.java
- chatty-be/src/main/java/com/chatty/chatty/user/service/UserService.java
- #441 
- 웹 소켓 재연결할 때 레디상태가 초기화되던 버그 수정
- SimpMessagingTemplate을 가진 커스텀 template 클래스를 구현하여 메소드 리팩토링
- 마이페이지 페이지네이션 버그 수정
- 퀴즈 결과 DTO에 유저 프로필이미지 추가
> [BE] 웹 소켓 재연결할 때 레디상태가 초기화되던 버그 수정

- chatty-fe/src/app/(game)/create-room/page.tsx
- chatty-fe/src/app/_api/createRoom.ts
> [feat/#446] :sparkles: feat: 100메가 초과 파일 업로드 시 얼럿

- chatty-fe/src/app/(game)/quiz-room/[id]/_components/ResultModal/ResultModal.tsx
- chatty-fe/src/app/(game)/quiz-room/[id]/page.tsx
- #448 
- 중간 결과 로직을 수정했습니다......................
> [feat/#448] :bug: fix: 로직 수정

- chatty-fe/src/app/(game)/quiz-room/[id]/page.css.ts
- chatty-fe/src/app/(game)/quiz-room/[id]/page.tsx
- chatty-fe/src/app/(game)/result/[id]/_components/ResultPageModal/ResultPageModal.tsx
- chatty-fe/src/app/(game)/result/[id]/page.tsx
- #450 
- 스트링 비교 -> marking 체크
- 문제풀이 페이지 상태 창 항상 자리 차지하게 변경
> [FE] 로직 수정

- chatty-be/src/main/java/com/chatty/chatty/auth/jwt/JwtUtil.java
- chatty-be/src/main/java/com/chatty/chatty/config/WebSocketEventListener.java
- chatty-be/src/test/java/com/chatty/chatty/auth/jwt/JwtUtilTest.java
- chatty-be/src/test/java/com/chatty/chatty/helper/MockBeanInjection.java
- #457 
- 토큰에서_유저Id를_가져온다
- 리프레쉬_토큰이_만료되었는지_확인한다
> [BE] JwtUtil 클래스 테스트 작성 

- chatty-be/src/test/java/com/chatty/chatty/auth/jwt/JwtUtilTest.java
> [feat/#457] :recycle: Refactor: 주석 제거

- chatty-be/src/test/java/com/chatty/chatty/auth/jwt/JwtUtilTest.java
> [feat/#457] :test_tube: Test: 테스트 확인을 위해 한 줄 추가

- chatty-be/src/test/java/com/chatty/chatty/auth/jwt/JwtUtilTest.java
> [feat/#457] 🧪 : Test: pr 생성 시 테스트 돌아가는지 확인

- chatty-fe/src/app/_components/BgmComponent/BgmComponent.tsx
- chatty-fe/src/app/_components/Header/Header.tsx
- chatty-fe/src/app/_store/useBgmStore.ts
- chatty-fe/src/app/page.tsx
> [feat/#467] :bug: fix: 브금 자동재생 수정

- chatty-fe/public/images/Empty_profile.svg
- chatty-fe/src/app/(game)/enter-room/[id]/_component/BlockingModal/BlockingModal.tsx
- chatty-fe/src/app/(game)/mypage/_component/UserInfoForm/UserInfoForm.tsx
- chatty-fe/src/app/(game)/waiting-room/[id]/_components/QuizInfoCard/QuizInfoCard.tsx
- chatty-fe/src/app/(game)/waiting-room/[id]/_components/ReadyButton/ReadyButton.css.ts
- chatty-fe/src/app/(game)/waiting-room/[id]/_components/UserCard/UserCard.css.ts
- chatty-fe/src/app/(game)/waiting-room/[id]/_components/UserCard/UserCard.tsx
- chatty-fe/src/app/(game)/waiting-room/[id]/_components/UserList/UserList.css.ts
- chatty-fe/src/app/(game)/waiting-room/[id]/_components/UserList/UserList.tsx
- chatty-fe/src/app/_components/Header/Header.css.ts
- chatty-fe/src/app/_components/Header/Header.tsx
> [FE] 헤더 프로필 연결, 대기방 반응형 일부 수정

- chatty-be/build.gradle
- chatty-be/src/main/java/com/chatty/chatty/auth/service/AuthService.java
- chatty-be/src/main/java/com/chatty/chatty/auth/support/BCryptPasswordEncoder.java
- chatty-be/src/main/resources/application-prod.yml
- chatty-be/src/test/java/com/chatty/chatty/auth/controller/AuthControllerTest.java
- #462 
- 테스트 작성 : AuthController - 일반 회원가입하면 토큰을 반환한다
- spring security 의존성 제거
- security 에서 사용하던 비밀번호 인코딩 클래스를 직접 구현 이후 적용 리팩토링
> [BE] Test: AuthController - 일반 회원가입하면 토큰을 반환한다

- chatty-fe/src/app/(game)/quiz-room/[id]/page.tsx
- chatty-fe/src/app/(game)/result/[id]/_components/ResultPageModal/ResultPageModal.css.ts
- #478 
- 엔터 제출 두 번 되던거 preventDefault로 수정
- 결과 페이지 컨테이너 오버플로우 수정
> [FE] 엔터 제출 두 번 수정, 결과 페이지 style 수정

- model/app/app.py
- model/app/data/keyword.py
- model/app/data/preprocessor.py
- #354 
- okt, nltk 객체를 초기에 생성하도록 수정
> [ML] 방생성 동시 요청 시 jdk 에러 발생

- chatty-fe/src/app/(game)/_components/AuthCheck.tsx
- chatty-fe/src/app/(game)/create-room/_components/DropBox/DropBox.tsx
- chatty-fe/src/app/(game)/create-room/_components/FileUploadBox.tsx
- chatty-fe/src/app/(game)/create-room/page.tsx
- chatty-fe/src/app/_api/createRoom.ts
- chatty-fe/src/middleware.ts
> [FE] 기존 퀴즈 가져오기

- index.html
- style.css
> [main] 깃헙 페이지 수정

- chatty-be/src/main/java/com/chatty/chatty/game/exception/ModelExceptionType.java
- chatty-be/src/main/java/com/chatty/chatty/game/service/model/ModelService.java
> [BE] :sparkles: Feat: 데이터 서버 예외 status에 따른 백엔드 서버 예외 추가

- model/app/app.py
- model/app/data/keyword.py
> [ML] Fix: 예외 발생하면 id생성하지 않도록 수정

- model/app/app.py
- model/app/data/keyword.py
Reverts Team-WeQuiz/wequiz#501
> Revert "[ML] Fix: 예외 발생하면 id생성하지 않도록 수정"

- model/app/data/keyword.py
> [ML] Fix: No features in text -> langdetect 가능한 최소 텍스트 길이 설정

- chatty-fe/src/app/(game)/mypage/_component/ProfileEditor/ProfileEditor.css.ts
- chatty-fe/src/app/(game)/waiting-room/[id]/_components/QuizInfoCard/QuizInfoCard.tsx
- chatty-fe/src/app/(game)/waiting-room/[id]/_components/UserCard/UserCard.tsx
- chatty-fe/src/app/(game)/waiting-room/[id]/_components/UserList/UserList.tsx
- chatty-fe/src/app/_components/Header/Header.css.ts
> [FE] 퀴즈봇 프로필 수정

- chatty-fe/src/app/(game)/quiz-room/[id]/page.tsx
- #516 
- keydown => keypress 교체
> [feat/#516] :bug: fix: 엔터 제출 에러 픽스

- chatty-fe/src/app/(game)/quiz-room/[id]/page.tsx
- chatty-fe/src/app/_api/quiz.ts
- #518 
- 새로고침 시 퀴즈가 진행되도록 수정
- 마지막 모달 카운트 끝나면 퀴즈 끝냄 알림 전송
> [FE] 새로고침 시 퀴즈 진행 / 마지막 퀴즈 알림

- model/app/app.py
- model/app/data/keyword.py
- model/app/data/preprocessor.py
- model/app/data/tokenizer.py
- #525 
- 객체풀 생성해서 사용 후 반납하도록 함.
> [ML] konlpy 객체 미리 생성 및 재사용을 위한 객체풀 생성

- model/app/utils/security.py
> [ML] openai api key 변경

- chatty-fe/src/app/(game)/quiz-room/[id]/page.tsx
- chatty-fe/src/app/_api/quiz.ts
- #521 
- 새로고침 후 submitstatus 에서 로직을 체크하여 제출 막기 활성화
> [FE] 새로고침 후 제출 상태 반영 안되던 문제 픽스

- chatty-fe/src/app/(game)/quiz-room/[id]/page.tsx
- chatty-fe/src/app/_api/quiz.ts
- chatty-fe/src/app/_components/BgmComponent/BgmComponent.tsx
- #523 
- autoplay 파라미터를 isPlaying으로 수정하여 UI 표시와 동일하게 브금이 재생되도록 수정
> [FE] bgm 버그 픽스

- chatty-fe/src/app/(game)/waiting-room/[id]/_components/ChatInput/ChatInput.tsx
- chatty-fe/src/app/(game)/waiting-room/[id]/page.tsx
- chatty-fe/src/app/_types/ChatType.ts
- chatty-fe/src/app/_types/WaitingStatus.ts
- #536 
- ChatType enum 제거 (혹시 몰라서 ChatType.ts 파일명은 변경 안 했습니다!)
- 채팅 요청할 때 chatType 제거
- 테스트해서 동작하는 거 확인했습니다!
> [FE] :bug: Fix: 채팅에서 chatType 삭제

- chatty-fe/src/app/(game)/quiz-room/[id]/_components/AnswerArea/AnswerArea.css.ts
- chatty-fe/src/app/(game)/quiz-room/[id]/_components/QuestionArea/QuestionArea.css.ts
- chatty-fe/src/app/(game)/quiz-room/[id]/_components/QuestionProgress/QuestionProgess.tsx
- chatty-fe/src/app/(game)/quiz-room/[id]/_components/QuestionProgress/QuestionProgress.css.ts
- chatty-fe/src/app/(game)/quiz-room/[id]/_components/UserGrid/UserGrid.css.ts
- chatty-fe/src/app/(game)/quiz-room/[id]/_components/UserGrid/UserGrid.tsx
- chatty-fe/src/app/(game)/quiz-room/[id]/page.css.ts
- chatty-fe/src/app/(game)/quiz-room/[id]/page.tsx
- chatty-fe/src/app/(game)/waiting-room/[id]/_components/ReadyButton/ReadyButton.tsx
- chatty-fe/src/app/_components/BarSpinner/BarSpinner.css.ts
> [FE] 퀴즈 풀이방 반응형 적용
